all: 
		g++ -c main.cpp
			g++ main.o -o knapsack
clean:
		rm *.o knapsack
		rm result_ks_4_0.txt
		rm result_ks_19_0.txt
		rm result_ks_30_0.txt
		rm result_ks_40_0.txt
		rm result_ks_45_0.txt
		rm result_ks_50_0.txt
		rm result_ks_50_1.txt
		rm result_ks_60_0.txt
		rm result_ks_100_0.txt
		rm result_ks_100_1.txt
		rm result_ks_100_2.txt
		rm result_ks_200_0.txt
		rm result_ks_200_1.txt
		rm result_ks_300_0.txt
		rm result_ks_400_0.txt
		rm result_ks_500_0.txt
		rm result_ks_1000_0.txt
		rm result_ks_10000_0.txt
